# Generated by Django 5.2 on 2025-05-26 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_table_servicecall"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecall",
            options={"ordering": ["-created_at"]},
        ),
    ]
