# Generated by Django 5.2 on 2025-07-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_servicecall_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecall",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
